# Setup
title:               My Pages
tagline:             
description:         'My Profile Site.'
url:                 
baseurl:             ''
paginate:            5
# permalink:           pretty

# About/contact
author:
  name:              redsappan
  url:               https://twitter.com/redsappan
  #email:             
# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
